name: get_version
description: Get the Version Name, Version Code, Platform and OS Version, and App ID on iOS and Android.
version: 0.0.8+4
author: Rody Davis <rody.davis.jr@gmail.com>
homepage: https://github.com/AppleEducate/plugins

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  package_info:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.appleeducate.getversion
    pluginClass: GetVersionPlugin
