name: get_version
description: Get the Version Name, Version Code, Platform and OS Version, and App ID on iOS and Android.
version: 0.0.8+5
author: Rody Davis <rody.davis.jr@gmail.com>
homepage: https://github.com/AppleEducate/plugins

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info: ^0.4.0+1

flutter:
  plugin:
    androidPackage: com.appleeducate.getversion
    pluginClass: GetVersionPlugin