name: mobile_sidebar
description: A Flutter plugin to show a sidebar on tablet and desktop then a list or gridview on mobile.
version: 1.5.0
author: Rody Davis Jr <rody.davis.jr@gmail.com>
homepage: https://github.com/AppleEducate/plugins

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^1.1.2
  localstorage: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
